<?php


class wg_tipo_cambio extends WP_Widget
{

    protected $defaults;


    function __construct()
    {

        $this->defaults = array(
            'title' => 'Sample Title',
            'url' => 'http://intranetap/services/ticker/rates.json'
        );

        $widget_options = array(
            'classname' => 'wg_tipo_cambio',
            'description' => 'Widget para mostrar el tipo de cambio de Interbanco'
        );

        $control_options = array(
            'id_base' => 'wg_tipo_cambio',
        );


        parent::__construct('wg_tipo_cambio', 'Widget para mostrar el tipo de cambio', $widget_options, $control_options);


    }


    function form($instance)
    {
        /**Merge with defaults**/
        $instance = wp_parse_args((array)$instance, $this->defaults);

        //write_log($instance);

        ?>

        <div>
            <label for="<?php echo $this->get_field_id('title'); ?>">Titulo</label>
            <input class="widefat" id="<?php echo $this->get_field_id('title'); ?>"
                   name="<?php echo $this->get_field_name('title'); ?>" type="text"
                   value="<?php echo esc_attr($instance['title']); ?>"/>
        </div>

        <div>
            <label for="<?php echo $this->get_field_id('url'); ?>">Url</label>
            <input class="widefat" id="<?php echo $this->get_field_id('url'); ?>"
                   name="<?php echo $this->get_field_name('url'); ?>" type="text"
                   value="<?php echo esc_attr($instance['url']); ?>"/>
        </div>

        <?php
    }


    function update($newinstance, $oldinstance)
    {


//        foreach ($newinstance as $key => $value) {
//
//        }

        return $newinstance;
    }

    /**
     * Widget Output.
     *
     * Outputs the actual widget on the front-end based on the widget options the user selected.
     *
     */

    function widget($args, $instance)
    {
        extract($args);

        /** Merge with defaults */
        $instance = wp_parse_args((array)$instance, $this->defaults);

        echo $args['before_widget'];

//        if (!empty($instance['title'])) {
//            echo $args['before_title'] . apply_filters('widget_title', $instance['title'], $instance, $this->id_base) . $args['after_title'];
//        }


        $tipo_cambio = consultar_tipo_cambio($instance['url']);


        write_log($tipo_cambio);

        ?>

        <!-- ticker tipo de cambio -->
        <div class="interbanco_widget_box interbanco_wg_tipo_cambio">

            <div class="clip_circle_mod icon_mod icn_tipo_cambio"></div><!-- icono del módulo-->

            <div id="interbanco_widget_header">
                <span class="txt_titulo"><?php echo $instance['title'] ?></span>
            </div>

            <div class="barra_ticker">
                <div>
                    <div class="tick_bold">USD</div>
                    <span>compra <?php echo number_format_i18n((double)$tipo_cambio->CompraGeneral,2) ?> - venta <?php  echo number_format_i18n((double)$tipo_cambio->VentaGeneral,2) ?></span>
                </div>
                <div>
                    <div>EUR</div>
                    <span>compra <?php echo number_format_i18n((double)$tipo_cambio->CompraGeneral_EURQTZ,2) ?> - venta <?php  echo number_format_i18n((double)$tipo_cambio->VentaGeneral_EURQTZ,2) ?></span>
                </div>
            </div><!-- fin barra ticker -->

        </div> <!-- FIN ST BOX-->
        <!-- fin ticker tipo de cambio -->
        <?php


        //if ($output) {
        //    printf('<a href="%s">Link</a>', $output);
        //}

        echo $args['after_widget'];


        //parent::widget($args, $instance); // TODO: Change the autogenerated stub
    }


}


add_action('widgets_init', 'interbanco_load_widget');
/**
 * Widget Registration.
 *
 * Register Simple Social Icons widget.
 *
 */
function interbanco_load_widget()
{

    register_widget('wg_tipo_cambio');

}